permissions:
  contents: write

# .github/workflows/build.yml
name: Build e Release

# Só roda quando você criar uma tag tipo v1.0.0
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-latest

    steps:
      # 1) Puxa o código
      - name: Checkout
        uses: actions/checkout@v3

      # 2) Seta Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 3) Instala dependências e PyInstaller
      - name: Install Dependencies
        run: pip install -r requirements.txt

      # 4) Gera o .exe usando o arquivo .spec
      - name: Build EXE com arquivo .spec
        run: pyinstaller "classificador_de_Imagens.spec"

      # 5) Empacota num ZIP
      - name: Zip App
        run: Compress-Archive -Path "dist\Classificador de Imagens\*" -DestinationPath "Classificador-de-Imagens.zip"

      # 6) Cria a Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: true
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 7) Anexa o ZIP à Release criada
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: Classificador-de-Imagens.zip
          asset_name: Classificador-de-Imagens-${{ github.ref_name }}.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
